### ISSUE TITLE
rate limit error

### ISSUE THREAD

**Issue by the1plummie** [uber/rides-python-sdk#31]
I'm getting rate limited even tho I'm only making 2 requests every 5 min, or 24 requests/hour. According to [this doc](https://developer.uber.com/docs/riders/guides/rate-limiting) we're allowed 2000 requests/hour... what gives?

My app id: mytestappnewyo
thanks.

**Comment by agraebe** [comment]
Please provide us with reproduction steps - including the endpoints (+version), SDK version, cURL/command/code with values (except for tokens,secrets,client_id), and logs/errors you're seeing.

**Comment by the1plummie** [comment]
uber-rides (0.3.0)

code snippet:
```
# removed last 2 decimal points, don't want to post exact locations
places = {
    'home': { 'lat': 34.0518, 'long': -118.4610 },
    'work': { 'lat': 33.9921, 'long': -118.4734 },
}

def _get_estimate_response(api_client, places['home'], places['work']):
    resp = api_client.get_products(*orig.values())
    products = resp.json.get('products')
    response = api_client.estimate_ride(
        product_id=products[0].get('product_id'),
        start_latitude=orig['lat'],
        start_longitude=orig['long'],
        end_latitude=dest['lat'],
        end_longitude=dest['long'],
        seat_count=1
    )
    return products, response
```

**Comment by agraebe** [comment]
Could you also add the log/error message?

**Comment by the1plummie** [comment]
sure, see below

```
(uber) shouguoli@builder:~/test/uber-rides$ python -u example/estimate.py
Traceback (most recent call last):
  File "example/estimate.py", line 187, in <module>
    get_estimate(name_orig='home', name_dest='work', detail=False)
  File "example/estimate.py", line 146, in get_estimate
    products1, response1 = _get_estimate_response(api_client, orig, dest)
  File "example/estimate.py", line 164, in _get_estimate_response
    resp = api_client.get_products(*orig.values())
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/uber_rides/client.py", line 124, in get_products
    return self._api_call('GET', 'v1.2/products', args=args)
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/uber_rides/client.py", line 104, in _api_call
    return request.execute()
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/uber_rides/request.py", line 155, in execute
    return self._send(prepared_request)
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/uber_rides/request.py", line 140, in _send
    return Response(response)
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/uber_rides/request.py", line 54, in __init__
    self.rate_limit = response.headers['X-Rate-Limit-Limit']
  File "/home/shouguoli/.virtualenvs/uber/local/lib/python2.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: u'x-rate-limit-limit'
```

**Comment by agraebe** [comment]
@the1plummie thanks. That was very helpful! It appears this is an issue with the SDK. We're [deprecating the rate limiting headers](https://medium.com/uber-developers/announcing-riders-api-1-2-featuring-upfront-fares-ride-promotions-and-improved-dev-docs-7745135ca33f#.8f01olghz) for v1.2 endpoints and the SDKs is actively looking for them. I'll create an issue for that.
