### ISSUE TITLE
Can't call client.estimate_ride with server_token

### ISSUE THREAD

**Issue by vankhoa011** [uber/rides-python-sdk#33]
Hello,

I need to call `client.estimate_ride` which authenticate by server_token.

However, It show the error. 

```
>>> result = client.estimate_ride(
...     product_id='cafb57ec-5157-4462-8453-09a7fc01f5d1',
...     start_latitude=10.7212701,
...     start_longitude=106.61727189999999,
...     end_latitude=10.7718007,
...     end_longitude=106.7044406
... )
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/uber_rides/client.py", line 326, in estimate_ride
    return self._api_call('POST', 'v1.2/requests/estimate', args=args)
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/uber_rides/client.py", line 104, in _api_call
    return request.execute()
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/uber_rides/request.py", line 152, in execute
    return self._send(prepared_request)
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/uber_rides/request.py", line 136, in _send
    response = session.send(prepared_request)
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/requests/sessions.py", line 615, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/Users/khoa/.virtualenvs/sosanhgiataxi/lib/python3.5/site-packages/uber_rides/utils/handlers.py", line 60, in error_handler
    raise ClientError(response, error_message)
uber_rides.errors.ClientError: 401: Invalid OAuth 2.0 credentials provided.
```

**Comment by dustinwhittle** [comment]
In order to create a fare_id via the estimate ride you must use a valid user access token. The estimate_ride endpoint creates an upfront_fare for a ride on behalf of a user.

In this case the error is you are using a server_token and not a user access_token. I realized the doc is incorrect - the example should be:

`response = client.get_price_estimates(
    start_latitude=37.770,
    start_longitude=-122.411,
    end_latitude=37.791,
    end_longitude=-122.405,
    seat_count=2
)

prices = response.json.get('prices')`
